# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# composer dump-env prod

parameters:
    php_errors_log: true
    container.dumper.inline_factories: true
    
    #app.another_constant: !php/const App\Entity\BlogPost::MAX_ITEMS

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Queue/'
            - '../src/Service/**/ServiceInternal/*'
            - '../src/Kernel.php'
            - '../tests'
    
    Araz\MicroService\AmqpConnection:
        arguments:
            $transport:
                dsn: '%env(QUEUE_AMQP_DSN)%'
                lazy: true
                persisted: true
                heartbeat: 10
                qos_prefetch_count: 1

    
    Araz\MicroService\Queue:
        arguments:
            $appName: 'micro-test-app'
            $connection: '@Araz\MicroService\AmqpConnection'
            $logger: '@logger'
            $container: '@parameter_bag'
            $enableClient: true
            $enableConsumer: true
            $processorConsumers:
                - 'App\Queue\Consumer\ConsumerFirst'
                - 'App\Queue\Consumer\ConsumerSecond'
        

    Araz\Service\User\UserService:
        arguments:
            $queue: '@Araz\MicroService\Queue'